### ISSUE TITLE
How could I inject it in a target process ?

### ISSUE THREAD

**Issue by Bonjour123** [xoofx/ManagedJit#2]
Hello @xoofx ! 
Let's say I want to hook a method in a .NET target process. What should I change to get it to work ?
I'm quite a beginner in C# hooks, so could you lead me on the steps I should follow ? 
I tried using the excellent injector [Xenos](https://github.com/DarthTon/Xenos). When it loads, as the target process doesn't call any method of the ManagedJit Dll, no code at all should be executed, yes ? However, I get System.Reflection.TargetInvocationException as soon as I interact with the UI of the target process.
How is it possible ?  Do I have to adapt something before ?

Thanks :)

PS: Oh je ne m'étais pas douté un instant que tu était français ^^ Super article, et le seul récent (celui de code project datant un peu, et surtout que pour x86) sur le sujet :+1:

**Comment by xoofx** [comment]
> Let's say I want to hook a method in a .NET target process. What should I change to get it to work ?
I'm quite a beginner in C# hooks, so could you lead me on the steps I should follow ?

Giving you exact advice on this would require me to look into how to do it precisely, but I really don't have spare time for this. You need to provide at least more context/code example that you are using to do this, so that I can spot an obvious error in your code. One thing to keep in mind is that ManagedJit requires perfect .NET version matching (the `ICorJitCompiler_getVersionIdentifier_index`)

**Comment by Bonjour123** [comment]
Ok, sure I understand. Ok, will keep this in mind. The second thing I wanted to understand is why just loading it inside the target process could be the cause of some exception. As the target process never call any method of the ManagedJit Dll, shouldn't it just be in the memory but never be executed ? 

Also, I get exceptions when I interact with a button of the UI, after the injection. So, to me, it means the first allegation 'but never be executed ' is false. Even more, if I interact even only once with this button (and so all the calls that follow in background), then inject and click again on this button, every thing works perfectly, I don't get any exceptions. So to me the hook on CompileMethod is set. BUT (yes, another one ..) if I put in every function which participates in installing the hook, for debug purposes:

     System.IO.File.WriteAllText(@"D:\\TestFromCSharp.txt", "Hello from ManagedJit\n");
..nothing is written to the file. 

So, tu sum up:
- how/why the 'install hook' function is called when loaded ? If you confirm me that it's not the standard behavior, then I guess it's Xenos which starts it
- Why my debug texts are not written, if we consider the hook have been indeed set ?

Thank you a lot in advance !

**Comment by xoofx** [comment]
again, I can't respond to these questions without actual simple code. (I don't understand this question `h ow/why the 'install hook' function is called when loaded ?` this is too general). Try to come with a very simple program you want to hook, start simple, put it on github, if you have a specific problem exception to the code where it doesn't work as expected, Then I can view if you are doing something wrong or not and where (but really, I can't promise, if it is too big, I won't time to have a look at it)

**Comment by Bonjour123** [comment]
It was a problem at the level of the injector, which was allowing me to do something that was restricted, i.e. not implemented. And for a reason or another, wasn't producing any errors for it. Thanks you for the help !
